- hosts: targets
  become: true
  vars:
    work_dir: /opt/ansible
    report_file: report.csv
  tasks:
    - name: Create a report directory
      file:
        path: "{{ work_dir }}"
        state: directory

    - name: Copy script
      copy:
        src: parse_hadoop_logs.py
        dest: "{{ work_dir }}"
        mode: 0555

    - name: Run script
      shell: "{{ ansible_python.executable }} {{ work_dir }}/parse_hadoop_logs.py"
      register: output

    - name: print output
      debug:
        var: output.stdout

